// Code generated by mockery v1.0.0
package mocks

import gocql "github.com/gocql/gocql"
import mock "github.com/stretchr/testify/mock"

// cqlSession is an autogenerated mock type for the cqlSession type
type cqlSession struct {
	mock.Mock
}

// Query provides a mock function with given fields: stmt, values
func (_m *cqlSession) Query(stmt string, values ...interface{}) *gocql.Query {
	var _ca []interface{}
	_ca = append(_ca, stmt)
	_ca = append(_ca, values...)
	ret := _m.Called(_ca...)

	var r0 *gocql.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *gocql.Query); ok {
		r0 = rf(stmt, values...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocql.Query)
		}
	}

	return r0
}
