// Code generated by mockery v1.0.0
package mocks

import cassandra "github.com/kalmanb/datapipelinepoc/rest/cassandra"
import mock "github.com/stretchr/testify/mock"

// QueryInterface is an autogenerated mock type for the QueryInterface type
type QueryInterface struct {
	mock.Mock
}

// Bind provides a mock function with given fields: _a0
func (_m *QueryInterface) Bind(_a0 ...interface{}) cassandra.QueryInterface {
	var _ca []interface{}
	_ca = append(_ca, _a0...)
	ret := _m.Called(_ca...)

	var r0 cassandra.QueryInterface
	if rf, ok := ret.Get(0).(func(...interface{}) cassandra.QueryInterface); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.QueryInterface)
		}
	}

	return r0
}

// Exec provides a mock function with given fields:
func (_m *QueryInterface) Exec() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Iter provides a mock function with given fields:
func (_m *QueryInterface) Iter() cassandra.IterInterface {
	ret := _m.Called()

	var r0 cassandra.IterInterface
	if rf, ok := ret.Get(0).(func() cassandra.IterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.IterInterface)
		}
	}

	return r0
}

// Scan provides a mock function with given fields: _a0
func (_m *QueryInterface) Scan(_a0 ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, _a0...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(_a0...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
