// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	schema.proto

It has these top-level messages:
	KafkaEvent
	Event
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KafkaEvent struct {
	Data             *Event                     `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	UtcGeneratedTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=utc_generated_time,json=utcGeneratedTime" json:"utc_generated_time,omitempty"`
}

func (m *KafkaEvent) Reset()                    { *m = KafkaEvent{} }
func (m *KafkaEvent) String() string            { return proto.CompactTextString(m) }
func (*KafkaEvent) ProtoMessage()               {}
func (*KafkaEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KafkaEvent) GetData() *Event {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KafkaEvent) GetUtcGeneratedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.UtcGeneratedTime
	}
	return nil
}

type Event struct {
	Id        uint32                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Account   uint32                     `protobuf:"varint,3,opt,name=account" json:"account,omitempty"`
	Amount    int64                      `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Field1    string                     `protobuf:"bytes,5,opt,name=field1" json:"field1,omitempty"`
	Field2    string                     `protobuf:"bytes,6,opt,name=field2" json:"field2,omitempty"`
	Field3    string                     `protobuf:"bytes,7,opt,name=field3" json:"field3,omitempty"`
	Field4    string                     `protobuf:"bytes,8,opt,name=field4" json:"field4,omitempty"`
	Field5    string                     `protobuf:"bytes,9,opt,name=field5" json:"field5,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetAccount() uint32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Event) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Event) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *Event) GetField2() string {
	if m != nil {
		return m.Field2
	}
	return ""
}

func (m *Event) GetField3() string {
	if m != nil {
		return m.Field3
	}
	return ""
}

func (m *Event) GetField4() string {
	if m != nil {
		return m.Field4
	}
	return ""
}

func (m *Event) GetField5() string {
	if m != nil {
		return m.Field5
	}
	return ""
}

func init() {
	proto.RegisterType((*KafkaEvent)(nil), "main.KafkaEvent")
	proto.RegisterType((*Event)(nil), "main.Event")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x14, 0x84, 0x95, 0x34, 0x4d, 0xc9, 0x2b, 0x20, 0xe4, 0x01, 0x59, 0x5d, 0x1a, 0x75, 0xca, 0xe4,
	0x8a, 0xa4, 0x95, 0xf8, 0x03, 0x08, 0x24, 0xb6, 0x88, 0xbd, 0x7a, 0xb5, 0x9d, 0x60, 0x51, 0xc7,
	0x55, 0xeb, 0xc0, 0x8f, 0x67, 0x41, 0x71, 0x1a, 0x93, 0xb1, 0xe3, 0x7d, 0x77, 0xbe, 0xf3, 0x83,
	0xdb, 0x33, 0xff, 0x94, 0x1a, 0xd9, 0xf1, 0x64, 0xac, 0x21, 0x91, 0x46, 0xd5, 0x2c, 0x96, 0xb5,
	0x31, 0xf5, 0x41, 0xae, 0x1d, 0xdb, 0xb7, 0xd5, 0xda, 0x2a, 0x2d, 0xcf, 0x16, 0xf5, 0xb1, 0x8f,
	0xad, 0x7e, 0x00, 0xde, 0xb1, 0xfa, 0xc2, 0x97, 0x6f, 0xd9, 0x58, 0xb2, 0x84, 0x48, 0xa0, 0x45,
	0x1a, 0xa4, 0x41, 0x36, 0xcf, 0xe7, 0xac, 0xeb, 0x60, 0xce, 0x2a, 0x9d, 0x41, 0xde, 0x80, 0xb4,
	0x96, 0xef, 0x6a, 0xd9, 0xc8, 0x13, 0x5a, 0x29, 0x76, 0x5d, 0x1f, 0x0d, 0x5d, 0x7c, 0xc1, 0xfa,
	0x31, 0x36, 0x8c, 0xb1, 0x8f, 0x61, 0xac, 0x7c, 0x68, 0x2d, 0x7f, 0x1d, 0x1e, 0x75, 0x78, 0xf5,
	0x1b, 0xc0, 0xb4, 0x1f, 0xbd, 0x87, 0x50, 0x09, 0x37, 0x79, 0x57, 0x86, 0x4a, 0x90, 0x67, 0x48,
	0xfc, 0x2f, 0xaf, 0xa8, 0xfe, 0x0f, 0x13, 0x0a, 0x33, 0xe4, 0xdc, 0xb4, 0x8d, 0xa5, 0x13, 0x57,
	0x37, 0x48, 0xf2, 0x08, 0x31, 0x6a, 0x67, 0x44, 0x69, 0x90, 0x4d, 0xca, 0x8b, 0xea, 0x78, 0xa5,
	0xe4, 0x41, 0x3c, 0xd1, 0x69, 0x1a, 0x64, 0x49, 0x79, 0x51, 0x9e, 0xe7, 0x34, 0x1e, 0xf1, 0xdc,
	0xf3, 0x82, 0xce, 0x46, 0xbc, 0xf0, 0x7c, 0x43, 0x6f, 0x46, 0x7c, 0xe3, 0xf9, 0x96, 0x26, 0x23,
	0xbe, 0xdd, 0xc7, 0xee, 0x90, 0xe2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x77, 0x12, 0x76, 0xb4,
	0x01, 0x00, 0x00,
}
